export const enum KeyColumn {
  ID = 'ID',
  NAME = 'NAME',
  ACTIVE = 'ACTIVE',
  FOR_APPLICATION_SECRETS = 'FOR_APPLICATION_SECRETS',
  CREATION_DATE_TIME = 'CREATION_DATE_TIME',
  APPLICATION_ID = 'APPLICATION_ID',
  SIGNING_KEY = 'SIGNING_KEY'
}
