export const enum ApplicationColumn {
  ID = 'ID',
  NAME = 'NAME',
  ENDPOINT_URL = 'ENDPOINT_URL',
  ACTIVE = 'ACTIVE',
  CREATION_DATE_TIME = 'CREATION_DATE_TIME',
  CAN_RESET_USER_PASSWORD = 'CAN_RESET_USER_PASSWORD',
  CAN_VERIFY_USER_EMAIL = 'CAN_VERIFY_USER_EMAIL',
  ADDED_USERS_ARE_ACTIVE = 'ADDED_USERS_ARE_ACTIVE',
  USERS_ARE_ADDED_ON_TOKEN_REQUEST = 'USERS_ARE_ADDED_ON_TOKEN_REQUEST'


}
